pipeline:
  identifier: Build_AFT_1686600546961
  name: Build AFT
  orgIdentifier: default
  projectIdentifier: TF
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1686012759285
        repoName: intekhab1025/AFT
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
